"""fix booking notify_id

Revision ID: 20d4b1d14495
Revises: 78e47a467286
Create Date: 2025-11-30 15:02:08.425400

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20d4b1d14495"
down_revision: Union[str, None] = "78e47a467286"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "booking",
        "notification_task_id",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "booking",
        "notification_task_id",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
