"""add admin history

Revision ID: 35b4fcbeeb13
Revises: a65ef663550a
Create Date: 2026-02-25 18:38:34.184681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b4fcbeeb13'
down_revision: Union[str, None] = 'a65ef663550a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('moderator_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('slot_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('BAN', 'UNBAN', 'GRANT_ADMIN', 'REVOKE_ADMIN', 'CHANGE_SLOT', name='admin_action'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_history_action'), 'admin_history', ['action'], unique=False)
    op.create_index(op.f('ix_admin_history_created_at'), 'admin_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_history_moderator_id'), 'admin_history', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_admin_history_slot_id'), 'admin_history', ['slot_id'], unique=False)
    op.create_index(op.f('ix_admin_history_target_user_id'), 'admin_history', ['target_user_id'], unique=False)
    op.drop_column('booking', 'notification_task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('notification_task_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_admin_history_target_user_id'), table_name='admin_history')
    op.drop_index(op.f('ix_admin_history_slot_id'), table_name='admin_history')
    op.drop_index(op.f('ix_admin_history_moderator_id'), table_name='admin_history')
    op.drop_index(op.f('ix_admin_history_created_at'), table_name='admin_history')
    op.drop_index(op.f('ix_admin_history_action'), table_name='admin_history')
    op.drop_table('admin_history')
    # ### end Alembic commands ###
