"""init schema

Revision ID: 42f85a36d5eb
Revises:
Create Date: 2025-11-30 00:06:22.677600

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "42f85a36d5eb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "type", sa.Enum("WASHING", "DRYING", name="slot_type"), nullable=False
        ),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("cso", sa.Integer(), nullable=False),
        sa.Column("row", sa.Integer(), nullable=False),
        sa.Column("place", sa.Integer(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_banned", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "booking",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("notification_task_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NEW", "CANCELLED", "DONE", name="booking_status"),
            nullable=False,
        ),
        sa.Column(
            "type", sa.Enum("WASHING", "DRYING", name="booking_type"), nullable=False
        ),
        sa.Column(
            "starts_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_notification_task_id"),
        "booking",
        ["notification_task_id"],
        unique=False,
    )
    op.create_index(op.f("ix_booking_user_id"), "booking", ["user_id"], unique=False)
    op.create_table(
        "notify",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notify_user_id"), "notify", ["user_id"], unique=False)
    op.create_table(
        "bookingslots",
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("slot_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["booking.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["slot_id"], ["slot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("booking_id", "slot_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookingslots")
    op.drop_index(op.f("ix_notify_user_id"), table_name="notify")
    op.drop_table("notify")
    op.drop_index(op.f("ix_booking_user_id"), table_name="booking")
    op.drop_index(op.f("ix_booking_notification_task_id"), table_name="booking")
    op.drop_table("booking")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("slot")
    # ### end Alembic commands ###
